### ISSUE TITLE
Starargs and varargs nodes do not have attributes set

### ISSUE THREAD

**Issue by casutton** [serge-sans-paille/gast#28]
On Python 2.7

In [1]: import gast

In [2]: src = """
   ...: def f(x, y, *a):
   ...:   return x * y
   ...: """

In [3]: gast.dump(gast.parse(src), include_attributes=True)
AttributeError: 'Name' object has no attribute 'lineno'

This does not occur under Python 3.5.

What seems to be happening AFAICT is that the arguments nodes do not have lineno and col_offset attributes, so the `ast.copy_location` calls in ast2.py on lines 135 and 141 do nothing.

I am not sure what the best way to fix this would be: the parent of the arguments node (if any) would have the correct location information, or it would be possible to call `fix_missing_locations` on the parent at the end, but both are a little bit messy to put into the visitor.

Full stack trace:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-c943fbb81c1a> in <module>()
----> 1 gast.dump(gast.parse(src), include_attributes=True)

/usr/lib/python2.7/ast.pyc in dump(node, annotate_fields, include_attributes)
    108     if not isinstance(node, AST):
    109         raise TypeError('expected AST, got %r' % node.__class__.__name__)
--> 110     return _format(node)
    111 
    112 

/usr/lib/python2.7/ast.pyc in _format(node)
     92     def _format(node):
     93         if isinstance(node, AST):
---> 94             fields = [(a, _format(b)) for a, b in iter_fields(node)]
     95             rv = '%s(%s' % (node.__class__.__name__, ', '.join(
     96                 ('%s=%s' % field for field in fields)

/usr/lib/python2.7/ast.pyc in _format(node)
    104             return rv + ')'
    105         elif isinstance(node, list):
--> 106             return '[%s]' % ', '.join(_format(x) for x in node)
    107         return repr(node)
    108     if not isinstance(node, AST):

/usr/lib/python2.7/ast.pyc in <genexpr>((x,))
    104             return rv + ')'
    105         elif isinstance(node, list):
--> 106             return '[%s]' % ', '.join(_format(x) for x in node)
    107         return repr(node)
    108     if not isinstance(node, AST):

/usr/lib/python2.7/ast.pyc in _format(node)
     92     def _format(node):
     93         if isinstance(node, AST):
---> 94             fields = [(a, _format(b)) for a, b in iter_fields(node)]
     95             rv = '%s(%s' % (node.__class__.__name__, ', '.join(
     96                 ('%s=%s' % field for field in fields)

/usr/lib/python2.7/ast.pyc in _format(node)
     92     def _format(node):
     93         if isinstance(node, AST):
---> 94             fields = [(a, _format(b)) for a, b in iter_fields(node)]
     95             rv = '%s(%s' % (node.__class__.__name__, ', '.join(
     96                 ('%s=%s' % field for field in fields)

/usr/lib/python2.7/ast.pyc in _format(node)
    101                 rv += fields and ', ' or ' '
    102                 rv += ', '.join('%s=%s' % (a, _format(getattr(node, a)))
--> 103                                 for a in node._attributes)
    104             return rv + ')'
    105         elif isinstance(node, list):

/usr/lib/python2.7/ast.pyc in <genexpr>((a,))
    101                 rv += fields and ', ' or ' '
    102                 rv += ', '.join('%s=%s' % (a, _format(getattr(node, a)))
--> 103                                 for a in node._attributes)
    104             return rv + ')'
    105         elif isinstance(node, list):

AttributeError: 'Name' object has no attribute 'lineno'

**Comment by serge-sans-paille** [comment]
Thanks for reporting o/

**Comment by casutton** [comment]
Awesome, thanks for the quick response! -cas

Sent from my iPhone; please excuse tyops

> On 25 Feb 2019, at 13:16, serge-sans-paille <notifications@github.com> wrote:
> 
> Thanks for reporting o/
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
