### ISSUE TITLE
Incompatibility with astunparse

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/gast#32]
In astunparse/unparser.py, there is something like

```
    boolops = {ast.And: 'and', ast.Or: 'or'}
    boolops[op.__class__]
```

So we get something like:
```
boolops[gast.And]                                                  
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-1cb576efff8e> in <module>
----> 1 boolops[gast.And]

KeyError: <class 'gast.gast.And'>
```

Could it be solved from gast ?

It would be nice to be able to do (just for And and Or): `{ast.And: "and"}[gast.And]`

How can one unparse a tree produced with gast ?

**Comment by paugier** [comment]
I found a simple solution for Transonic so it is not really a problem.

https://bitbucket.org/fluiddyn/transonic/src/8d5255e10bd6e9cfaede309cf53b3bd63f083e15/transonic/analyses/extast.py#lines-33

**Comment by serge-sans-paille** [comment]
I would have called ``gast.gast_to_ast(node)`` before unparsing, that should work flawlessly

**Comment by paugier** [comment]
Yes! Thanks!
