### ISSUE TITLE
Ellipsis symbol missing

### ISSUE THREAD

**Issue by mdanatg** [serge-sans-paille/gast#35]
Hi, it seems that the 0.3 release is missing some symbols like `Ellipsis`. Is this intentional?

**Comment by serge-sans-paille** [comment]
No, that's a bug. Did you spot any other missing symbol?

**Comment by axch** [comment]
Didn't check precisely, but the documentation seems to imply that `Num`, `Str`, `Bytes`, and `NameConstant` may be gone, too.  Presumably in favor of `Constant`.

**Comment by serge-sans-paille** [comment]
> Num, Str, Bytes, and NameConstant may be gone, too

Yes, that's a change implied by the evolution of python3.8. Actually `ast.Ellipsis` will be modelized as an `ast.Constant(value=Ellipsis, type=None)` too.

**Comment by serge-sans-paille** [comment]
@mdanatg #36 should fix Ellipsis support. Please note that `ast.Ellipsis` as a node disappears in favor of `ast.Constant(value=Ellipsis, type=None)` There are some slight changes wrt how `ast.ExtSlice` behave too, that's detailed in the README update.
