### ISSUE TITLE
could you please create 0.3.2 tag

### ISSUE THREAD

**Issue by daqingshu** [serge-sans-paille/gast#38]
I found the v0.3.2 https://pypi.org/project/gast/#files
but there is no tag

**Comment by serge-sans-paille** [comment]
Fixed: https://github.com/serge-sans-paille/gast/tree/0.3.2

**Comment by daqingshu** [comment]
> Fixed: https://github.com/serge-sans-paille/gast/tree/0.3.2

tks :)
