### ISSUE TITLE
User should be able to use same boolean literal AST nodes on Python 2 and Python 3

### ISSUE THREAD

**Issue by jfinkels** [serge-sans-paille/gast#4]
Currently, in gast 0.1.4, Python 2 has `Name(id='True')` but Python 3 has `NameConstant(value=True)`.
```sh
$ python2 -c "import gast; print(gast.dump(gast.parse('True')))"
Module(body=[Expr(value=Name(id='True', ctx=Load(), annotation=None))])
$ python3 -c "import gast; print(gast.dump(gast.parse('True')))"
Module(body=[Expr(value=NameConstant(value=True))])
```
I expected `NameConstant(value=True)` in both situations.

**Comment by serge-sans-paille** [comment]
That's a design choice : the following is valid Python 2 code :+1: 
```
True = 3
print(True)
```

so one cannot use a ``NameConstant`` to represent ``True``

**Comment by jfinkels** [comment]
Okay, I get it. Python 2 is annoying :)

In that case, it might be worth a mention in the documentation somewhere, because I was surprised by this.
