### ISSUE TITLE
Add some helpers for creating visitors

### ISSUE THREAD

**Issue by samvv** [serge-sans-paille/gast#40]
Hi, this really is a great library. Thanks for making it! May I suggest one improvement? It would be really useful if this library contained the basic boilerplate for creating visitors.

I was thinking of an `expand` function that yields the child nodes of the node that is given to it. Something like this:

```py
def expand(node):
  if isinstance(node, Module):
    for stmt in node.body:
      yield stmt
     for type_ignore in node.type_ignores:
      yield type_ignore
  elif isinstance(node, Interactive):
   # and so on ...
```

I don't know if this is within the scope of this project, but it would be terribly useful to have. For example, I would be able define the following:

```py
def preorder(root, expand):
    stack = [root]
    while len(stack) > 0:
        node = stack.pop()
        yield node
        for node in expand(top):
            stack.append(root)
```

And use it like so:

```py
import gast

def has_return_stmt(node):
  for node in preorder(node, gast.expand):
    if isinstance(node, gast.Return):
      return True
  return False
```

I haven't looked at the code of this library yet, but if you want I can try to add this functionality.

**Comment by serge-sans-paille** [comment]
Hi and thanks for the kind words. Is that really different from `gast.iter_child_nodes` and/or `gast.walk ` ? Their documentation is (or should be!) the same as `ast.iter_child_nodes` and `ast.walk`.

Out of curiosity: what are you using gast for?

**Comment by samvv** [comment]
Hi, you're welcome! I haven't used the default visitors myself yet. Actually, they might be sufficient now I come to think of it 😅I think the main advantage of this piece of code (there's now a pull request) is that you can specify yourself how you want to perform the expansion. Preorder, postorder, inorder, ... Also, because it is a generator, you can halt execution at any time. Maybe that's an argument in favour of this extension?

I'm using GAST in a toy compiler I'm writing that re-uses the Python syntax. It's mainly to practice my skills a bit 😃 Incidentally, the toy language will also be used in [Templaty](https://github.com/samvv/Templaty), a template engine for generating programming code.

**Comment by samvv** [comment]
Ok, looks like it is exactly the same as `iter_child_nodes`. Note to self: take a better look at the documentation next time.
