### ISSUE TITLE
Publish sdist and bdist wheel

### ISSUE THREAD

**Issue by groodt** [serge-sans-paille/gast#42]
The benefits of wheels are well documented. See: https://pythonwheels.com/
This package is pure Python and publishing it as both source and as a wheel is simple

Would you accept a PR that adds a simple Makefile or documentation that describes how to release this package as both a sdist and bdist_wheel?

**Comment by serge-sans-paille** [comment]
I'm okay with publishing both bdist_wheel and sdist, but I don't feel an extra doc : Makefile in the repo for it makes sense :-)

Just added a wheel build for gast 0.3.2, please tell me if I did something wrong!

**Comment by groodt** [comment]
Great! Thanks!

I don’t yet see the wheel on
https://pypi.org/project/gast/

Also maybe overkill, but we could add cibuildwheel
https://github.com/joerick/cibuildwheel
to automate releases when you tag on GitHub.

**Comment by serge-sans-paille** [comment]
@groodt should be fixed as of 0.3.3, see https://pypi.org/project/gast/#files. Can you confirm the wheels are functional?

**Comment by groodt** [comment]
Thanks  @serge-sans-paille 

Looks good to me!
