### ISSUE TITLE
module 'gast' has no attribute 'Index'

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [serge-sans-paille/gast#53]
**System information**
- source: **https://www.tensorflow.org/tutorials/text/transformer**
- OS Platform: **ArchLinux 5.8.14 x86_64**
- TensorFlow installed from (source or binary): **binary** : https://www.archlinux.org/packages/community/x86_64/tensorflow-cuda/
- TensorFlow version (use command below): **2.3.1** -2
- Python version: **3.8.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **11.1.0** -2 https://www.archlinux.org/packages/community/x86_64/cuda/
- GPU model and memory: GeForce GTX 1660 SUPER computeCapability: 7.5,  22 deviceMemorySize: 5.80GiB

**Describe the current behavior**
```
WARNING:tensorflow:AutoGraph could not transform 
<function train_step at 0x7f15c0790ee0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, 
set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
```

**Describe the expected behavior**

**Standalone code to reproduce the issue**
python transformer.py

**Other info / logs** Include any logs or source code that would be helpful to
[transformer.zip](https://github.com/tensorflow/tensorflow/files/5402845/transformer.zip)

**Comment by serge-sans-paille** [comment]
Thanks for reporting! This is likely to be a packaging issue. I see tensorflow-cuda depends on python-tensorflow which itself depends on python-gast.

The version provided py archlinux for python-gast is 0.4.0, but it loos like tensorflow still depends on gast 0.3.0. Maybe @mdanatg can confirm the status?

It's probably worth opening a bug issue on the archlinux side, stating  that packaged tensorflow should consider pinning the gast version (?)

**Comment by mdanatg** [comment]
Yes, TensorFlow depends on gast 0.3.3, but a change pushed yesterday accidentally moved the version number to 0.4. The change is being rolled back, and should land soon.
