### ISSUE TITLE
[incompatible] Why ExtSlice and Index are not used after gast 3.9 ? 

### ISSUE THREAD

**Issue by liym27** [serge-sans-paille/gast#55]
"For minor version before 3.9, please note that ExtSlice and Index are not used." 

My project used gast 0.3.3, which has gast.Index and my project rely on the analysis of gast.Index. Now it's upgraded to version 0.4.0, gast.Index is removed, which cause incompatibility. 

For example:
```
source = "a[i]"

gast_node = gast.parse(source)
print(gast.dump(ast_node))
```
Before 3.9
```
Module(body=[Expr(value=Subscript(value=Name(id='a', ctx=Load(), annotation=None, type_comment=None), slice=Index(value=Name(id='i', ctx=Load(), annotation=None, type_comment=None)), ctx=Load()))], type_ignores=[])
```
NOTE: slice=Index(value=Name(...))

After 3.9
```
Module(body=[Expr(value=Subscript(value=Name(id='a', ctx=Load(), annotation=None, type_comment=None), slice=Name(id='i', ctx=Load(), annotation=None, type_comment=None), ctx=Load()))], type_ignores=[])
```
NOTE: slice=Name(...), Index is removed.

**Comment by serge-sans-paille** [comment]
Hi @liym27, and thanks for the feedback.
`gast` policy is to follow as closely as possible recent version of the `ast` module, while still being able to represent former version of Python `ast`. The change you're pointing at is a consequence of Python 3.9 no longer using `ast.Index`, and we follow that approach in `gast`.

So basically you can either pin your gast version, but you loose py39 support, or upgrade your codebase :-)

**Comment by liym27** [comment]
Thanks.
