### ISSUE TITLE
GitHub CI doesn't test Python 2

### ISSUE THREAD

**Issue by atsampson** [serge-sans-paille/gast#66]
`setup.py` and `tox.ini` both claim to support Python 2.7, but the GitHub CI only runs the tests on Python 3 at the moment - so I'm not sure if the intention is still to support Python 2 or not.

(There are some Python 3-isms in `gast/unparse.py` that cause test failures with gast 0.5.3 on Python 2: at least the definition of `_ALL_QUOTES`, `*` arguments, and various `f""` strings...)

**Comment by serge-sans-paille** [comment]
@atsampson I missed that one. Can you confirm #67 fixes the issue on your side?

**Comment by atsampson** [comment]
That looks good to me - I've applied the patch from that branch to 0.5.3 and all the tests pass for me now. Thanks very much!
