### ISSUE TITLE
why ast not support [] () to use in express

### ISSUE THREAD

**Issue by lxm9704** [serge-sans-paille/gast#68]
i have a code to be parsed like this
`self.atom(_func=self.vm_list[0].try_execute, _args='pkill iperf3')`
but i can't find list's index info in ast_obj,how can i deal with this express?

**Comment by serge-sans-paille** [comment]
Hi and thanks for the report. The following works like a breeze, I don't understand your issue (indentation is mine)

```
>>> import gast
>>> gast.dump(gast.parse("self.atom(_func=self.vm_list[0].try_execute, _args='pkill iperf3')"))
"Module(
    body=[
        Expr(value=
            Call(func=Attribute(value=Name(id='self', ctx=Load(), annotation=None, type_comment=None), attr='atom', ctx=Load()), args=[],
            keywords=[
                keyword(arg='_func', value=Attribute(value=Subscript(value=Attribute(value=Name(id='self', ctx=Load(), annotation=None, type_comment=None), attr='vm_list', ctx=Load()), slice=Constant(value=0, kind=None), ctx=Load()), attr='try_execute', ctx=Load())),
                keyword(arg='_args', value=Constant(value='pkill iperf3', kind=None))
            ] )
        )
    ],
    type_ignores=[]
)"

```

**Comment by lxm9704** [comment]
oh...so that's another thing that troubled me,how can i change the parse info to get original info. i means that i got the parse info
`keyword(arg='_func', value=Attribute(value=Subscript(value=Attribute(value=Name(id='self', ctx=Load(), annotation=None, type_comment=None), attr='vm_list', ctx=Load()), slice=Constant(value=0, kind=None), ctx=Load()), attr='try_execute', ctx=Load()))`
how can i change it to `_func=self.vm_list[0].try_execute`
if there any easy function to use? 
thanks
