### ISSUE TITLE
Making nodes actual subclasses of standard library nodes

### ISSUE THREAD

**Issue by tristanlatr** [serge-sans-paille/gast#75]
Hi @serge-sans-paille, 

I’m opening this issue to propose a change in the node generation process: that is to actually make gast nodes subclasses of standard library nodes, so that `isinstance` checks becomes compatible with standard library. This could ease adoption of gast since it would considerably reduce the amount of incompatibilities with the standard library.

Tell me what you think,

**Comment by serge-sans-paille** [comment]
it's already the case for non-final types like `stmt` or `expr`. But for final types like `FunctionDef` this would be a source of confusion, as some fields would be there twice, some would be there while they shouldn't be... I don't quite want to go that way.
