### ISSUE TITLE
Errors while Parsing Python2 code

### ISSUE THREAD

**Issue by KarthickRaja2002** [serge-sans-paille/gast#77]
Hi @serge-sans-paille ,

Need some clarifications regarding GAST parsing for **Python2** source code.

1. Getting error while parsing Python2 **Print statement**.
`
print "Hello"
`
> **SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?**

2. Showing error while having **indentation issues in Python2** version code
```
class checkExistingUser(models.Model): #1
	privatekey = models.CharField(max_length=250, blank=True) #2
        emailid =  models.CharField(max_length=250,blank=True) #3
```
Got error in Line 3

> **TabError: inconsistent use of tabs and spaces in indentation**

I need to know that whether the module can be **able to parse Python2** version code.

Thanks in Advance.

**Comment by serge-sans-paille** [comment]
I assume you're invoking gast from python3. What gast does is provide a generic AST for each python version. It can convert code from the python version it's running on to its AST. What gast doesn't provide is a python parser for another version than the one it's running on.
