### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [serge-sans-paille/gast#78]
Is it possible next time on release new version make the github release to have entry on https://github.com/serge-sans-paille/gast/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.
My automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by serge-sans-paille** [comment]
Hey @kloczek , I don't plan on using github release as it's redundant with the tag I use to mark release, esp. as tags are recorded in the git repo while github release are specific to github.

You can follow https://github.com/serge-sans-paille/gast/tags.atom to be updated on new tags, or

https://pypi.org/rss/project/gast/releases.xml

to be updated on pypi release.

**Comment by kloczek** [comment]
Adding git tag does not generate **email notifications**.
If you don't care about informing other people interested that new release has been made that is fine but if you care it make sense to add GH release.
You already using github workflows so it can be easily added
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026

**Comment by serge-sans-paille** [comment]
I'll stick to pypi + tag as of now, as described above there are already several ways to consume the releases programmatically.

**Comment by kloczek** [comment]
Thank you 👍 😄
